Bug: fails on group create/edit with error.
To reproduce, create a new group using page /admin/groups/edit. If you hit submit with an empty group name you get an error,

Error: InvalidArgumentException Route [users.groups.edit] not defined.

This bug affects all cases where an error might occur during group create or edit. I've proposed a change to the route in the redirect from "users.groups.edit" to "groups.edit".

I hope that's an appropriate solution. Maybe there's a better one?